import type { Metadata } from 'next'
import { Ubuntu as FontSans } from 'next/font/google'
import './globals.css'
import {ReactNode} from "react";
import {cn} from "@/lib/utils";

export const fontSans = FontSans({
  variable: '--font-sans',
  weight: ['300'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
      )}>{children}</body>
    </html>
  )
}
